-- ============================================================
-- Bulk gym import (Becky 제공 리스트 → 정규화 + dedupe)
--
-- 전처리:
--   1. 기존 21 시드의 name에서 공백을 제거해 import 형식과 통일
--      ('클라이밍 파크' → '클라이밍파크', '서울숲 클라이밍' → '서울숲클라이밍')
--      gym_id 보존 → grade_votes / sessions / problems FK 유지
--   2. gyms(name, branch) UNIQUE 제약 추가 (NULLS NOT DISTINCT로 null branch도 묶음)
--   3. import 194 rows INSERT … ON CONFLICT DO NOTHING
--      - 16 dups (exact 14 + fuzzy 2 = 정규화 후 통일됨) 자동 skip
--      - 178 unique 신규 insert
--   4. 폐업 (더클라임 서울대점) 1개 제외 (입력 195 → 194)
--   5. 의심 중복 2쌍은 SQL 주석으로 표시, 둘 다 insert (사용자 검토 중)
-- ============================================================

update gyms set name = '클라이밍파크' where name = '클라이밍 파크';
update gyms set name = '서울숲클라이밍' where name = '서울숲 클라이밍';

alter table gyms
  add constraint gyms_name_branch_unique unique nulls not distinct (name, branch);

-- 클라이밍장 시드 데이터
-- 출처: 사용자(Becky) 제공 리스트 + 더클라임 공식 사이트 캡처
-- 위경도(latitude/longitude)는 NULL — 카카오 geocoding 후 별도 UPDATE 예정
-- 총 195개

insert into gyms (
  name, branch, city, district, address,
  latitude, longitude,
  has_boulder, has_lead, has_top_rope, has_speed, has_auto_belay,
  has_moonboard, has_kilter, has_tension,
  facilities, size_pyeong, floors_count, opened_at,
  parking_info, phone, website_url, instagram_handle, description
) values
  ('클라이밍파크', '강남점', '서울', '강남구', '서울 강남구 강남대로 364 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라이밍파크', '성수점', '서울', '성동구', '서울 성동구 연무장13길 7 매니아빌딩', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('더클라임', '강남점', '서울', '강남구', '서울 강남구 테헤란로8길 21 강남화인빌딩 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, '건물 외부 전용 계단 이용 (건물 내 엘리베이터/계단 이용 불가)', '02-566-8821', NULL, NULL, '평일 08:00~24:00 · 주말 08:00~22:00'),
  ('스톤즈클라이밍', NULL, '서울', '관악구', '서울 관악구 남부순환로 1990-3 닷컴힐즈 B201호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('서울숲클라이밍', '영등포점', '서울', '영등포구', '서울 영등포구 문래로 164 B동 1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('손상원 클라이밍짐', '을지로점', '서울', '중구', '서울 중구 남대문로 125 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('알레클라이밍', '영등포점', '서울', '영등포구', '서울 영등포구 영등포로33길 14', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('피커스(PEAKERS) 클라이밍', '신촌', '서울', '서대문구', '서울 서대문구 신촌로 129 아트레온 11층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('서울숲클라이밍', '종로점', '서울', '종로구', '서울 종로구 수표로 96 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('더클라임', '문래점', '서울', '영등포구', '서울 영등포구 당산로 63', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, '회차시간 10분 (입차후 10분이내 출차시 무료)', '02-3667-5014', NULL, NULL, '평일 07:00~24:00 · 주말 08:00~22:00'),
  ('서울숲클라이밍', '구로점', '서울', '구로구', '서울 구로구 디지털로 300 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('캐치스톤클라이밍짐', '부천역점', '경기', '부천시', '경기 부천시 원미구 부천로 11 잼존프라자 18층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('크래커 클라이밍', NULL, '서울', '중랑구', '서울 중랑구 면목로92길 37-4 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('손상원 클라이밍짐', '강남역점', '서울', '서초구', '서울 서초구 강남대로 331 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('서울숲클라이밍', '잠실점', '서울', '송파구', '서울 송파구 백제고분로7길 49 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('더플라스틱클라이밍', '염창점', '서울', '강서구', '서울 강서구 공항대로81길 27 1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('더클라임', '양재점', '서울', '강남구', '서울 강남구 남부순환로 2615 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, '2시간 무료, 이후 30분당 2,000원 / 현금결제 불가', '02-576-8821', NULL, NULL, '평일 08:00~24:00 · 주말 08:00~22:00'),
  ('더클라임', '연남점', '서울', '마포구', '서울 마포구 양화로 186 3층 (LC TOWER)', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, '지점 등록 시 30분 무료, 이후 10분당 1,000원 (출차시 결제)', '02-2088-5071', NULL, NULL, '평일 07:00~24:00 · 주말 08:00~22:00'),
  ('더클라임', '사당점', '서울', '관악구', '서울 관악구 과천대로 939 지하2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, '02-585-8821', NULL, NULL, '평일 08:00~24:00 · 주말 08:00~22:00'),
  ('레드원클라이밍 봉선', NULL, '광주', '남구', '광주 남구 봉선2로 81 가로수빌딩 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('오프더월 클라이밍', '이태원점', '서울', '용산구', '서울 용산구 이태원로 190 지하 2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('더클라임', '이수점', '서울', '동작구', '서울 동작구 동작대로 59 B1', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, '1시간 무료, 이후 15분 2,000원', '02-588-5014', NULL, NULL, '평일 08:00~24:00 · 주말 08:00~22:00'),
  ('캐치스톤클라이밍짐', '부천시청역점', '경기', '부천시', '경기 부천시 원미구 석천로 171 중동프라자 7층 701호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('비블럭클라이밍', '영종하늘도시점', '인천', '중구', '인천 중구 하늘중앙로195번길 18 6층 601-604호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('알레클라이밍', '강동점', '서울', '강동구', '서울 강동구 천호대로177길 39 지하 2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('더클라임', '일산점', '경기', '고양시', '경기 고양시 일산동구 중앙로 1160 5층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, '4시간 500원, 이후 15분당 500원', '031-905-5014', NULL, NULL, '평일 08:00~24:00 · 주말 08:00~22:00'),
  ('더클라임', '논현점', '서울', '서초구', '서울 서초구 강남대로 519 B1', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, '02-545-5014', NULL, NULL, '평일 08:00~24:00 · 주말 08:00~22:00'),
  ('웨이브락 클라이밍', '남천점', '부산', '수영구', '부산 수영구 황령대로 473번길 15 남천 엑슬루타워 상가 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('더클라임', '신림점', '서울', '관악구', '서울 관악구 신원로 35 삼모더프라임타워 5층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, '3시간 1,000원 (지점 결제), 이후 10분당 1,500원 (출차시 결제)', '02-877-8821', NULL, NULL, '평일 07:00~24:00 · 주말 08:00~22:00'),
  ('더클라임', '성수점', '서울', '성동구', '서울 성동구 아차산로17길 49 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, '02-499-5014', NULL, NULL, '평일 08:00~24:00 · 주말 08:00~22:00'),
  ('클라이밍파크', '종로점', '서울', '종로구', '서울 종로구 종로 199 한일빌딩 지하2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라임투게더', '원주점', '강원', '원주시', '강원도 원주시 문막읍 동화골길 25', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('픽스볼더', '아라점', '제주', '제주시', '제주 제주시 중앙로768', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('피커스(PEAKERS) 클라이밍', '구로', '서울', '구로구', '서울 구로구 구로중앙로 152 NC신구로점 6층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('어웨이크 클라이밍', '타임월드점', '대전', '서구', '대전 서구 둔산로 18 향촌월드프라자 10F', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('킨디클라이밍', NULL, '경기', '수원시', '경기 수원시 권선구 세화로 124 1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('온플릭 클라이밍짐', '삼성점', '서울', '강남구', '서울 강남구 테헤란로 505 싹타워 B1', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('그루트 클라이밍', NULL, '서울', '성동구', '서울 성동구 성수일로19 유한타워 B2', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('코알라 클라이밍', '킨텍스', '경기', '고양시', '경기 고양시 일산서구 중앙로 1560-34 이마파킹프라자 B1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('락랜드 클라이밍', NULL, '서울', '강북구', '서울 강북구 도봉로 315 2F 락랜드클라이밍', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('볼더프렌즈 클라이밍', NULL, '서울', '마포구', '서울 마포구 홍익로 25 서교빌딩 지하3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('알레클라이밍', '혜화점', '서울', '종로구', '서울 종로구 창경궁로34길 18-5 토가빌딩 B2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('치즈클라이밍', NULL, '서울', '용산구', '서울 용산구 원효로 134 대교빌딩 지하 102호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('퍼즐클라이밍', NULL, '경기', '남양주시', '경기 남양주시 다산중앙로19번길 15 4층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('손상원 클라이밍짐', '판교점', '경기', '성남시', '경기 성남시 분당구 대왕판교로 670', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('더클라임', '신사점', '서울', '강남구', '서울 강남구 압구정로2길 6 지하2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, '02-549-8821', NULL, NULL, '평일 12:00~23:00 · 주말 토 10:00~22:00 / 일·공휴일 10:00~20:00'),
  ('슈퍼비클라이밍', NULL, '경기', '수원시', '경기 수원시 영통구 청명남로 40 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라임업', '수원점', '경기', '수원시', '경기 수원시 팔달구 권광로207번길 39 지산빌딩 4층 401호~403호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('훅클라이밍', '왕십리점', '서울', '성동구', '서울 성동구 고산자로6길 40 2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('볼더가든 클라이밍', NULL, '경기', '시흥시', '경기 시흥시 은계호수로 49 센트럴돔 3층 3043호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('신촌 담장', NULL, '서울', '서대문구', '서울 서대문구 신촌역로 10 5층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('더클라임', '마곡점', '서울', '강서구', '서울 강서구 마곡동로 62 마곡사이언스타워 7층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, '최대 3시간 1,000원 (데스크 할인), 이후 10분당 2,000원', '02-2668-5014', NULL, NULL, '평일 08:00~24:00 · 주말 08:00~22:00'),
  ('무중력 클라이밍', NULL, '서울', '강남구', '서울 강남구 논현로 563 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('피커스(PEAKERS) 클라이밍', '종로', '서울', '종로구', '서울 종로구 돈화문로5가길 1 지하 4층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('서울숲클라이밍', '뚝섬점', '서울', '성동구', '서울 성동구 성수일로 19 유한타워 B2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('비숍 클라이밍', NULL, '서울', '노원구', '서울 노원구 동일로 1393 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  -- 의심 중복 (드림캐처 vs 볼더 클라이밍짐): 동일 주소 노원구 상계로5길 32 7층. 사용자 검토 중, 둘 다 INSERT.
  ('드림캐처 클라이밍짐', NULL, '서울', '노원구', '서울 노원구 상계로5길 32 7층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('몽키즈클라이밍', '중계점', '서울', '노원구', '서울 노원구 한글비석로 359 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라임투더문 클라이밍', NULL, '서울', '송파구', '서울 송파구 백제고분로 224 창대빌딩 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라이밍파크', '신논현점', '서울', '강남구', '서울 강남구 강남대로 468 지하3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('온플릭 클라이밍짐', '천호점', '서울', '강동구', '서울 강동구 올림픽로 664 대우한강베네시티 상가 지하 1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('락트리 클라이밍', '강남', '서울', '강남구', '서울 강남구 강남대로118길 12 B2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('닷 클라이밍짐', NULL, '서울', '송파구', '서울 송파구 법원로8길 9 청림타워 2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('훅클라이밍', '성수점', '서울', '성동구', '서울 성동구 성수일로12길 34 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('볼더생활 클라이밍짐', NULL, '서울', '동작구', '서울 동작구 동작대로29길 69 7층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('온사이트 클라이밍', NULL, '서울', '강남구', '서울 강남구 테헤란로 505 싹타워 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('코알라클라이밍', '상암', '서울', '마포구', '서울 마포구 월드컵북로 396 누리꿈스퀘어 디지털파빌리온 B1040호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('볼더그라운드 클라이밍', NULL, '서울', '마포구', '서울 마포구 잔다리로 31 B1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라이밍파크', '한티점', '서울', '강남구', '서울 강남구 선릉로 324 SH타워 지하3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('락스타 클라이밍', NULL, '서울', '송파구', '서울 송파구 백제고분로 435 예스빌딩 B1', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라임잇 클라이밍', '구로점', '서울', '구로구', '서울 구로구 구로중앙로 215 지층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라임웍스 클라이밍', '영등포', '서울', '영등포구', '서울 영등포구 버드나루로 85 훼미리하우스117 지하 1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('에이스클라이밍센터', NULL, '서울', '구로구', '서울 구로구 가마산로27길 14 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('강서클라이밍센터', NULL, '서울', '강서구', '서울 강서구 공항대로 284 동서빌딩 4층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('을지로 담장', NULL, '서울', '중구', '서울 중구 마른내로 63-3 2F', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('타잔101 클라이밍', '압구정점', '서울', '강남구', '서울 강남구 압구정로28길 11 B1', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('행클라임 클라이밍짐', '구파발', '서울', '은평구', '서울 은평구 통일로 1020 은평뉴타운 신한헤센스마트 M204호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('정지현클라이밍짐', NULL, '서울', '관악구', '서울 관악구 봉천로 462 은일빌딩 7층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('어거스트클라이밍', NULL, '서울', '강서구', '서울 강서구 양천로 461 8층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('조규복클라이밍센터', '강변점', '서울', '광진구', '서울 광진구 구의강변로 45 1층 104호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('산타클라이밍', NULL, '서울', '동대문구', '서울 동대문구 난계로30길 23 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('더클라이밍짐', NULL, '서울', '서초구', '서울 서초구 서초대로46길 65 아주빌딩 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('브릭스클라이밍짐', NULL, '서울', '송파구', '서울 송파구 중대로 130 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('원베일리 인바이트 클라이밍', NULL, '서울', '서초구', '서울 서초구 반포대로 333 지하3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('볼더하이웨이클라이밍짐', NULL, '서울', '강남구', '서울 강남구 논현로86길 20 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('루트클라이밍', NULL, '서울', '송파구', '서울 송파구 양재대로71길 5-14 B1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라이밍88', NULL, '서울', '강서구', '서울 강서구 공항대로 376 제2체육관 1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('몽키즈클라이밍', '북가좌점', '서울', '서대문구', '서울 서대문구 응암로 54 5층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('인클라이밍센터', NULL, '서울', '관악구', '서울 관악구 남부순환로 1925 지층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('몽키즈클라이밍', '목동점', '서울', '양천구', '서울 양천구 목동동로 65 6층 601호 602호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('SUMMIT클라이밍센터', NULL, '서울', '마포구', '서울 마포구 신촌로24안길 14 1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('서울볼더스 선유', NULL, '서울', '영등포구', '서울 영등포구 양평로28마길 7 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('플래시볼더스', NULL, '서울', '중구', '서울 중구 서애로5길 21 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('서울볼더스 목동', NULL, '서울', '양천구', '서울 양천구 신목로 53 2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('더클라임 B', '홍대점', '서울', '마포구', '서울 마포구 양화로 125 경남관광빌딩', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  -- 의심 중복 (위 드림캐처와 동일 주소). 사용자 검토 중.
  ('볼더 클라이밍짐', NULL, '서울', '노원구', '서울 노원구 상계로5길 32 7층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라이밍 업더월 일산', NULL, '경기', '고양시', '경기 고양시 일산서구 경의로 805 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('페퍼클라이밍', NULL, '경기', '고양시', '경기 고양시 덕양구 권율대로 656 19층 1901호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라이밍 하이프렉스', NULL, '경기', '고양시', '경기 고양시 일산서구 덕이로 20 1E B1', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('더바이브클라이밍', '양주옥정점', '경기', '양주시', '경기 양주시 옥정동로7가길 36 메인타워 5층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  -- 의심 중복 (클라임크루 vs 마운틴스타): 동일 주소 양주시 평화로 1575-6. 사용자 검토 중, 둘 다 INSERT.
  ('클라임크루', NULL, '경기', '양주시', '경기 양주시 평화로 1575-6 나동', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('픽 클라이밍', NULL, '경기', '김포시', '경기 김포시 김포한강4로 507 계림M스퀘어 404호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('잼클라이밍', NULL, '경기', '김포시', '경기 김포시 김포한강2로 76 프레즌스빌딩 3층 301호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('키클 클라이밍', '풍무점', '경기', '김포시', '경기 김포시 풍무로146번길 14 9층 901호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('정글짐 클라이밍센터', NULL, '경기', '파주시', '경기 파주시 청암로17번길 53 월드타워8층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('킹클라이밍', NULL, '경기', '의정부시', '경기 의정부시 동일로 462 가동 7층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('샤모니 클라이밍', NULL, '경기', '의정부시', '경기 의정부시 경의로 48 벼룩시장건물 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('조규복클라이밍센터', '금곡점', '경기', '남양주시', '경기 남양주시 석실로 696', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('다이노 클라이밍짐', NULL, '경기', '남양주시', '경기 남양주시 다산중앙로146번길 12-14 7층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('엠투클라이밍', NULL, '경기', '남양주시', '경기 남양주시 다산순환로 356 푸리마타워 8층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  -- 의심 중복 (위 클라임크루와 동일 주소). 사용자 검토 중.
  ('마운틴스타 클라이밍짐', NULL, '경기', '양주시', '경기 양주시 평화로 1575-6 나동', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라임 어스', '미사점', '경기', '하남시', '경기 하남시 미사강변동로 81 13층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('락페이스클라이밍', NULL, '경기', '성남시', '경기 성남시 중원구 산성대로 340-1 범원빌딩 8층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라임 어스', '모란점', '경기', '성남시', '경기 성남시 중원구 성남대로 1126 6층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('락트리 클라이밍', '분당', '경기', '성남시', '경기 성남시 분당구 황새울로 224 청구블루빌 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('B Climbing', NULL, '경기', '성남시', '경기 성남시 분당구 백현로144번길 29-1 B1', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('더볼더 클라이밍', NULL, '경기', '성남시', '경기 성남시 분당구 미금일로90번길 36-5 5층 501호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('볼더메이트 클라이밍', '기흥점', '경기', '용인시', '경기 용인시 기흥구 기흥로 58 기흥ICT밸리 B동 지하2층 B225호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('볼더메이트 클라이밍', '수지점', '경기', '용인시', '경기 용인시 수지구 문정로 13 6층 601호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('경기레포츠클라이밍', NULL, '경기', '용인시', '경기 용인시 기흥구 흥덕1로 13 흥덕IT밸리 컴플렉스동 지하1층 P183호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라이밍 더 하기', NULL, '경기', '안성시', '경기 안성시 보개원삼로 147', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('프리월 클라이밍짐', NULL, '경기', '평택시', '경기 평택시 세교8길 30 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('트윈클라이밍짐', NULL, '경기', '평택시', '경기 평택시 평택3로 30 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('힐앤토클라이밍', NULL, '경기', '평택시', '경기 평택시 팽성읍 송화택지로 139 진영빌딩2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('마운틴그라운드 클라이밍', NULL, '경기', '화성시', '경기 화성시 동탄대로5길 15 그랑파사쥬 5층 5005호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('CL 클라이밍', NULL, '경기', '화성시', '경기 화성시 동탄대로 446 그란비아스타 6층 중앙 6123호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라임어클락', NULL, '경기', '화성시', '경기 화성시 동탄기흥로257번가길 33 동탄프리미엄아울렛 B동 113호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('볼더박스 클라이밍 경기 화성시', NULL, '경기', '화성시', '경기 화성시 경기대로 1038 4층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('문클라임', NULL, '경기', '화성시', '경기 화성시 동탄원천로 338 7층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('에픽클라임', NULL, '경기', '수원시', '경기 수원시 영통구 영통로 103 뉴엘지프라자 402호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('그래비티 클라이밍', '영통구청점', '경기', '수원시', '경기 수원시 영통구 효원로 400 탑프라자 7층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('그래비티클라이밍', '수원역점', '경기', '수원시', '경기 수원시 팔달구 갓매산로 31 홍익스포츠프라자 2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('포에버클라이밍', NULL, '경기', '수원시', '경기 수원시 영통구 영통로174번길 5 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('킹콩클라이밍', NULL, '경기', '수원시', '경기 수원시 팔달구 경수대로 572 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('뀨클라임', NULL, '경기', '수원시', '경기 수원시 영통구 청명남로34번길 12 7층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('언더독클라임', NULL, '경기', '수원시', '경기 수원시 팔달구 권광로207번길 39 4층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('에잇 픽스 클라이밍', NULL, '경기', '의왕시', '경기 의왕시 계원대학로 22 오남프라자 6층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('락클라이밍 산본', NULL, '경기', '군포시', '경기 군포시 광정로 60 우주타운빌딩 9층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('락클라이밍 산본', '클라이밍센터', '경기', '군포시', '경기 군포시 고산로 695 6층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라이밍 트리클', NULL, '경기', '안산시', '경기 안산시 단원구 화랑로 402 신원프라자 지하 1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클럽클라이밍', NULL, '경기', '안산시', '경기 안산시 단원구 고잔로 76 6층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('안산 베이스캠프 클라이밍', NULL, '경기', '안산시', '경기 안산시 단원구 광덕2로 185-20 골드프라자', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('에어즈락 클라이밍', '범계점', '경기', '안양시', '경기 안양시 동안구 시민대로 161 201호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('펀클라임짐 클라이밍', NULL, '경기', '안양시', '경기 안양시 동안구 시민대로327번길 6 지하1층 101호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라임데이즈 클라이밍', NULL, '경기', '안양시', '경기 안양시 만안구 덕천로152번길 25 안양아이에스BIZ타워센트럴 A동 217호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라임잇 클라이밍', '목감점', '경기', '시흥시', '경기 시흥시 배미골길 24 1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('시흥캐치클라이밍짐', NULL, '경기', '시흥시', '경기 시흥시 장곡동 250-2', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('매드짐 광명클라이밍센터', NULL, '경기', '광명시', '경기 광명시 범안로 1008 5층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('월드클라이밍', NULL, '경기', '부천시', '경기 부천시 원미구 상동로 90', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('팍스클라이밍', NULL, '경기', '부천시', '경기 부천시 오정구 소사로 680', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('타이거볼더 클라이밍짐', NULL, '경기', '부천시', '경기 부천시 원미구 부흥로307번길 52', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('허브클라이밍', NULL, '인천', '동구', '인천 남동구 논고개로123번길 17 아이플렉스빌딩 10층 1001', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라이밍줌', NULL, '인천', NULL, '인천 연수구 청능대로 75 7층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('디스커버리클라이밍 클라임스퀘어', '청라점', '인천', '서구', '인천 서구 청라라임로 71 진영메디피아 1002호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('간석클라이밍', NULL, '인천', '동구', '인천 남동구 경인로 520 탑프라자 602호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('볼리 클라이밍', NULL, '인천', '동구', '인천 남동구 서창남순환로216번길 30', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('서인천 클라이밍', NULL, '인천', '서구', '인천 서구 가정로 374 4층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('비블럭 클라이밍', '송도점', '인천', NULL, '인천 연수구 송도과학로16번길 13-39 107호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('디스커버리클라이밍 클라임스퀘어', '송도점', '인천', NULL, '인천 연수구 송도과학로16번길 33-4 트리플스트리트 D동 211a~c호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('디스커버리클라이밍 클라임스퀘어', 'ICN', '인천', '서구', '인천 서구 완정로 70 마전동 영남탑스빌 웰빙센터 5층', NULL, NULL, true, true, false, false, true, false, false, false, '{}', NULL, 1, NULL, '주차 가능', '032-715-5014', 'http://www.climbingsquare.kr', NULL, '평일 ~23:00 · 일일 20,000원 / 자유이용(1개월) 130,000원 / 기초입문강습 180,000원'),
  ('그립픽클라이밍짐', NULL, '경기', '성남시', '경기 성남시 수정구 위례광장로 104 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('스튜디오볼더', NULL, '서울', '구로구', '서울 구로구 디지털로33길 11 지하1층 B101호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('웨이브락 클라이밍', '부산대점', '부산', '금정구', '부산 금정구 장전온천천로 51 테라스파크 2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('웨이브락 클라이밍', '광안점', '부산', '수영구', '부산 수영구 장대골로 41 제이비클래식빌딩 1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('웨이브락 클라이밍', '서면점', '부산', '부산진구', '부산 부산진구 서전로 9번길 20 혜도인파크에비뉴 상가 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라임투게더', '수원점', '경기', '수원시', '경기 수원시 영통구 덕영대로 1566 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('베이스캠프 볼더스팟 클라이밍', '유성점', '대전', '유성구', '대전 유성구 온천로 52 4층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('베이스캠프 볼더스팟 클라이밍', '둔산점', '대전', '서구', '대전 서구 대덕대로 243 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('하나클라이밍짐', NULL, '대전', '유성구', '대전 유성구 월드컵대로 32', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('대전클라이밍센터', NULL, '대전', '서구', '대전 서구 갈마로 163 지하1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('별클라이밍', NULL, '세종', NULL, '세종 보듬3로 158 101~104호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('홀드온클라이밍', NULL, '전북', '군산시', '전북 군산시 축동2길 39-4 1층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('군산스포츠클라이밍센터', NULL, '전북', '군산시', '전북 군산시 월명로 274 2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('지락펀락 클라이밍 센터', NULL, '전북', '익산시', '전북 익산시 인북로 325', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라임팜', NULL, '전북', '익산시', '전북 익산시 고봉로32길 34 2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('하드락 클라이밍센터', NULL, '전북', '전주시', '전북 전주시 완산구 바우배기1길 11 엠에스빌딩 5층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('한''S클라이밍센터', NULL, '전북', '전주시', '전북 전주시 덕진구 견훤로 146 4층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('전주올라클라이밍센터', NULL, '전북', '전주시', '전북 전주시 덕진구 송천중앙로 154 4층 401호', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('어센트클라이밍', '전북대', '전북', '전주시', '전북 전주시 덕진구 권삼득로 333 2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('어센트클라이밍', '만성', '전북', '전주시', '전북 전주시 덕진구 만성중앙로 76 청옥빌딩 6층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('BK클라이밍', NULL, '전북', '전주시', '전북 전주시 완산구 효동3길 7 익선빌딩4층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('카르페클라임 클라이밍센터', NULL, '전남', '무안군', '전남 무안군 삼향읍 대죽서로 41 금호프라자2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('원클라임', NULL, '전남', '순천시', '전남 순천시 해룡면 낙선길 2', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('공주숲클라이밍짐', NULL, '충남', '공주시', '충남 공주시 한적2길 29 신관동 노브랜드 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('서산클라이밍', NULL, '충남', '서산시', '충남 서산시 율지3로 1 광락빌딩 2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('고릴라클라이밍', NULL, '충남', '서산시', '충남 서산시 서해로 3443', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('락트리 클라이밍', '아산', '충남', '아산시', '충남 아산시 배방읍 고속철대로 63 5층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('클라임맥스 클라이밍', NULL, '충남', '천안시', '충남 천안시 동남구 신방동 768-40', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('청주락클라이밍센터', NULL, '충북', '청주시', '충북 청주시 청원구 율량로190번길 15 3층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('스포츠아일랜드 클라이밍 오창', NULL, '충북', '청주시', '충북 청주시 청원구 오창읍 과학산업3로 222 블루스퀘어 지하2층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('타기클라이밍센터', NULL, '충북', '청주시', '충북 청주시 상당구 단재로 293 3층 B1', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('오르락클라이밍짐', NULL, '충북', '충주시', '충북 충주시 호암수청1로 55 5층', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('넝쿨클라이밍센터', NULL, '충북', '충주시', '충북 충주시 국원대로 126', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
  ('픽스볼더', '연동점', '제주', '제주시', '제주 제주시 삼무로 41 B1', NULL, NULL, true, false, false, false, false, false, false, false, '{}', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL)
on conflict (name, branch) do nothing;
